server:
  port: 9090

spring:
  datasource:
#    url: jdbc:mysql://192.168.0.238:3306/local_station?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://192.168.0.11:3306/testSpringboot?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://127.0.0.1:3335/local_station?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.0.11:3306/local_station?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://119.3.42.30:53306/local_station?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ENC(c/Y2PZMYWlFjx7IbNCt8rhsuwLYVWhMI)
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #password: ENC(+yGpfuuKZ1uMmkwnU/Pho8TDZJL3OdjA)
    timeout: 1000ms
    jedis:
      pool:
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
        max-active: 8

  rabbitmq:
      host: localhost
      port: 5673
      username: rabbitmq
      password: 29G8CSIDJz$K
  servlet:
    multipart:
      enabled: true
      #单个文件大小限制
      max-file-size: 20MB
      #单个请求总的大小限制
      max-request-size: 200MB

#加载Mybatis映射文件
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.producehelper.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    cache-enabled: false
    map-underscore-to-camel-case: true
    local-cache-scope: statement
  global-config:
    db-config:
      id-type: auto

#数据库加密
jasypt:
  encryptor:
    password: zhnyxs

#令牌解密
encrypt:
  key-store:
    location: classpath:/zj.keystore
    secret: zhejiangkeystore
    alias: zjkey
    password: zhejiang

logging:
  level:
    org.springframework.web: INFO
    com.xingyi.pos: INFO


auth:
  tokenValiditySeconds: 43200  #token存储到redis的过期时间
  clientId: ZjWebApp  #客户端Id
  clientSecret: ZjWebApp  #客户端密码
  cookieDomain: 119.3.101.155  #
  cookieMaxAge: -1  #浏览器关闭cookie无效
  errorCount: 10   #密码错误的最大次数
  expTime: 43200000L
  signKey: "zj-project"


aoplog:
  enable: true
  more: true


#RSA加密配置
myRSA:
  pubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm2JU6phYwXPDXRF6b6WFOjtgMt8ErdpGQjfxVOw5HcZ8NbqdLJxJybViegwMgl/yV8/p2soJC3oyGzrnOwLp4GJJDwpGFanytlca8g/atT5qbjgvbiKrjtN2nVQqxQSOsrOBk5lKtjrcQvkzeEaqYB85vU88azAzdrDuCt+euNs9RFLzd4jk75Q2ZquMM+vcuTk54VXo+lLtY3wAszRD3CjjP7OyfxPNQCaCaKDMu+8uwzTBJpgj5qXRpNHA06uM7uqWknFBnnDgmHp7xet+IOKdAmcmjF8FQvg9pebeABIKMq2UwOvSmEHMVIYMWlndN/bcFxhuVqANPno1t/8dlQIDAQAB

file:
  sqlLogFile: runSql.log
